language: python

python:
  - '3.6'

service:
  - postgres

install:
  - pip3 install pipenv
  - pipenv install --system 

before_script:
  - export APP_SETTINGS='project.config.TestingConfig'
  - export DATABASE_TEST_URL=postgresql://postgres:@localhost/users_test
  - psql -c 'CREATE DATABASE users_test;' -U postgres
  - python manage.py recreate_db

script:
  - python manage.py test
