version: '3.1'

services:
  nginx:
    build: ./nginx/
    container_name: nginx
    image: flask-users-nginx
    restart: always
    ports: 
      - 80:80
    depends_on:
      - users-service

  users-service:
    container_name: users-service
    build: .
    image: flask-users-service
    command: gunicorn -b 0.0.0.0:5000 manage:app
    expose:
      - 5000
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db

  users-db:
    container_name: users-db
    build: ./project/db
    image: flask-users-db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
    healthcheck:
      test: exit 0
